Repository depromeet/16th-team1-FE, pull requests merged in 2025-03, with the labels that each got.

#74 [#68] - 디자인 시스템 (Text Input) 구현
  src/common/components/text-input/text-input-status.ts
  src/common/components/text-input/text-input.styles.ts
  src/common/components/text-input/text-input.tsx
  src/common/stories/text-input.stories.tsx
Labels: ✨ Feature

#76 [#70] - 사이드바 완성 디자인 적용
  package.json
  pnpm-lock.yaml
  src/assets/icons/logo-full.svg
  src/assets/icons/sidebar-menu-icon.svg
  src/common/stories/button.stories.tsx
  src/common/stories/sidebar.stories.tsx
  src/common/stories/toast.stories.tsx
  src/features/total-evaluation/components/accordion-list/accordion-list.tsx
  src/features/total-evaluation/components/accordion-list/feedback-contents.styles.ts
  src/features/total-evaluation/components/accordion-list/feedback-contents.tsx
  src/features/total-evaluation/components/accordion-list/single-accordion-item.styles.ts
  src/features/total-evaluation/components/accordion-list/single-accordion-item.tsx
  src/features/total-evaluation/components/context/selected-page/selected-page-context.tsx
  src/features/total-evaluation/components/context/selected-page/selected-page-provider.tsx
  src/features/total-evaluation/components/context/sidebar/sidebar-context.tsx
  src/features/total-evaluation/components/context/sidebar/sidebar-provider.tsx
  src/features/total-evaluation/components/custom-buttons/accordion-trigger-button.styles.ts
  src/features/total-evaluation/components/custom-buttons/accordion-trigger-button.tsx
  src/features/total-evaluation/components/custom-buttons/add-button.tsx
  src/features/total-evaluation/components/custom-buttons/page-location-button.styles.ts
  src/features/total-evaluation/components/custom-buttons/page-location-button.tsx
  src/features/total-evaluation/components/custom-buttons/project-title-button.styles.ts
  src/features/total-evaluation/components/custom-buttons/project-title-button.tsx
  src/features/total-evaluation/components/custom-buttons/sidebar-close-button.tsx
  src/features/total-evaluation/components/custom-buttons/sidebar-control-button.styles.ts
  src/features/total-evaluation/components/custom-buttons/sidebar-open-button.tsx
  src/features/total-evaluation/components/custom-buttons/single-content-button.styles.ts
  src/features/total-evaluation/components/custom-buttons/single-content-button.tsx
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.styles.ts
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.tsx
  src/features/total-evaluation/components/left-slide-panel-toggle/left-slide-panel-toggle.styles.ts
  src/features/total-evaluation/components/left-slide-panel-toggle/left-slide-panel-toggle.tsx
  src/features/total-evaluation/service/data.ts
  src/features/total-evaluation/total-evaluation-page.tsx
  src/features/total-evaluation/types/sidebar-Info-types.ts
Labels: ✨ Feature

#80 [#60] - 업로드 페이지 스타일 적용
  src/assets/icons/add-document.svg
  src/features/upload/components/file-upload/file-upload-button.styles.ts
  src/features/upload/components/file-upload/file-upload-button.tsx
  src/features/upload/components/file-upload/file-upload.styles.ts
  src/features/upload/components/file-upload/file-upload.tsx
  src/features/upload/upload-page.styles.ts
  src/features/upload/upload-page.tsx
Labels: 🎨 Style

#82 [#78] - 수정된 버튼 디자인 시스템 반영
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/preview.tsx
  package.json
  pnpm-lock.yaml
  src/assets/styles/button.ts
  src/assets/styles/space.ts
  src/common/components/button/Button.tsx
  src/common/components/button/base-button.styles.ts
  src/common/components/button/base-button.tsx
  src/common/components/button/button.styles.ts
  src/common/stories/button.stories.tsx
  src/common/stories/sidebar.stories.tsx
  src/features/upload/components/file-upload/file-upload-button.styles.ts
  src/features/upload/components/file-upload/file-upload-button.tsx
  src/features/upload/components/file-upload/file-upload.tsx
Labels: ✨ Feature, 🔨 Fix, 🧤 Refactor

#85 [#83] - 랜딩페이지 (자주 묻는 질문)
  src/assets/icons/leftArrow.svg
  src/features/landing/common/data.ts
  src/features/landing/components/frequently-asked-questions/frequently-asked-questions.styles.ts
  src/features/landing/components/frequently-asked-questions/frequently-asked-questions.tsx
  src/features/landing/landing-page.styles.ts
  src/features/landing/landing-page.tsx
  src/route.tsx
Labels: ✨ Feature

#87 [#86] - 랜딩페이지 FAQ 타이틀 및 아이콘 색상 수정
  src/assets/fonts/GeneralSans-Variable.woff2
  src/assets/styles/global-styles.ts
  src/features/landing/components/frequently-asked-questions/frequently-asked-questions.styles.ts
  src/features/landing/components/frequently-asked-questions/frequently-asked-questions.tsx
Labels: 🎨 Style

#90 [#88] - Colorsystem 수정사항 반영
  src/assets/styles/button.ts
  src/assets/styles/colors.ts
  src/assets/styles/global-styles.ts
  src/common/components/toast/toast.styles.ts
  src/features/landing/components/frequently-asked-questions/frequently-asked-questions.styles.ts
  src/features/landing/landing-page.styles.ts
  src/features/total-evaluation/components/custom-buttons/page-location-button.styles.ts
  src/features/total-evaluation/components/custom-buttons/project-title-button.styles.ts
  src/features/total-evaluation/components/left-slide-panel-toggle/left-slide-panel-toggle.styles.ts
Labels: 🎨 Style

#93 [#92] - 랜딩페이지 (포트폴리오 업로드 페이지로 라우팅하는 섹션) 퍼블리싱
  src/assets/icons/symbol.svg
  src/features/landing/components/routing-section/routing-bottom-section.tsx
  src/features/landing/components/routing-section/routing-section.styles.ts
  src/features/landing/components/routing-section/routing-start-section.tsx
  src/features/landing/landing-page.styles.ts
  src/features/landing/landing-page.tsx
Labels: 🎨 Style

#103 [#102] - Tanstack-query 데브툴즈 적용
  package.json
  pnpm-lock.yaml
  src/app.tsx
Labels: ⚙️ Chore

#105 [#101] - 랜딩페이지 세부 개선점 섹션 퍼블리싱
  public/images/improvement-01.png
  public/images/improvement-02.png
  public/images/improvement-03.png
  public/images/improvement-04.png
  public/images/improvement-05.png
  src/features/landing/common/data.ts
  src/features/landing/components/helpers-section/detail-improvement.styles.ts
  src/features/landing/components/helpers-section/detail-improvement.tsx
  src/features/landing/components/helpers-section/helpers-section.tsx
  src/features/total-evaluation/components/improvement-section/improvement-text.styles.ts
Labels: 🎨 Style

#99 [#98] - 사이드바 설계 로직 변경
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.tsx
  src/features/total-evaluation/components/left-slide-panel-toggle/left-slide-panel-toggle.styles.ts
  src/features/total-evaluation/components/left-slide-panel-toggle/left-slide-panel-toggle.tsx
  src/features/total-evaluation/components/sidebar/base-sidebar-left/base-sidebar-left.styles.ts
  src/features/total-evaluation/components/sidebar/base-sidebar-left/base-sidebar-left.tsx
  src/features/total-evaluation/components/sidebar/feedback-page-navigator/control-buttons.styles.ts
  src/features/total-evaluation/components/sidebar/feedback-page-navigator/control-buttons.tsx
  src/features/total-evaluation/components/sidebar/feedback-page-navigator/feedback-page-navigator.tsx
Labels: 🧤 Refactor

#94 [#81] - 모달 공통 컴포넌트, 최근 받은 피드백 확인 모달 구현
  package.json
  pnpm-lock.yaml
  src/assets/icons/close.svg
  src/assets/icons/feedback.svg
  src/assets/styles/fonts.ts
  src/common/components/modal/base-modal.styles.ts
  src/common/components/modal/base-modal.tsx
  src/features/profile/common/data.ts
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal.styles.ts
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal.tsx
  src/features/profile/util/parse-feedback-data.ts
  src/features/total-evaluation/components/logical-leap/logical-error.styles.ts
  src/store/modal.ts
Labels: ✨ Feature, 🧤 Refactor

#109 [#106] - 랜딩페이지 반응형 개선
  public/images/total-evaluation.png
  src/features/landing/common/data.ts
  src/features/landing/components/frequently-asked-questions/frequently-asked-questions.styles.ts
  src/features/landing/components/helpers-section/step-card.styles.ts
  src/features/landing/components/helpers-section/step-card.tsx
  src/features/landing/landing-page.styles.ts
  src/features/landing/landing-page.tsx
  src/features/total-evaluation/total-evaluation-page.tsx
  src/route.tsx
Labels: 🎨 Style, 🔨 Fix

#113 [#107] - 레이아웃 기본 구조 생성 및 임시 헤더 적용
  src/assets/icons/logo-header.svg
  src/assets/styles/button.ts
  src/common/components/button/Button.tsx
  src/common/components/header-navigation/header-navigation-layout.styles.ts
  src/common/components/header-navigation/header-navigation-layout.tsx
  src/common/components/layout/common-layout.styles.ts
  src/common/components/layout/common-layout.tsx
  src/common/constants/path.ts
  src/common/stories/button.stories.tsx
  src/common/utils/generateHederContents.tsx
  src/features/landing/components/navigation-buttons/navigation-buttons.styles.ts
  src/features/landing/components/navigation-buttons/navigation-buttons.tsx
  src/route.tsx
Labels: ✨ Feature

#114 [#108] - 피드백 대기 화면 퍼블리싱
  src/assets/icons/feedbackLoadingDownArrow.svg
  src/assets/video/logoSpinning.mp4
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal.styles.ts
  src/features/upload/components/feedback-loading/feedback-loading.styles.ts
  src/features/upload/components/feedback-loading/feedback-loading.tsx
Labels: 🎨 Style

#116 [#84] - 임시 로그인 페이지 배포(테스트용)
  package.json
  pnpm-lock.yaml
  src/assets/icons/google.svg
  src/assets/icons/logo-full-header-navigation.svg
  src/assets/icons/logo-full-login.svg
  src/assets/icons/logo-full.svg
  src/assets/icons/logo-header.svg
  src/common/components/auth/Authorization.tsx
  src/common/utils/generateHederContents.tsx
  src/features/login/components/custom-buttons/google-auth-button.styles.ts
  src/features/login/components/custom-buttons/google-auth-button.tsx
  src/features/login/login-page.styles.ts
  src/features/login/login-page.tsx
  src/features/total-evaluation/components/sidebar/feedback-page-navigator/control-buttons.tsx
  src/route.tsx
Labels: ✨ Feature

#118 [#117] - 로그인 리다이렉션 로직 제거
  src/common/components/auth/Authorization.tsx
Labels: 🚨 Bug, 🔨 Fix

#121 [#110] - 포트폴리오 피드백 조회 API 연동
  src/assets/icons/check.svg
  src/assets/icons/grade_A.svg
  src/assets/icons/grade_B.svg
  src/assets/icons/grade_C.svg
  src/assets/icons/grade_D.svg
  src/assets/icons/triangle.svg
  src/assets/icons/x.svg
  src/common/constants/path.ts
  src/common/utils/generateHederContents.tsx
  src/features/total-evaluation/common/data.ts
  src/features/total-evaluation/components/evaluation-chart/evaluation-chart.styles.ts
  src/features/total-evaluation/components/evaluation-chart/evaluation-chart.tsx
  src/features/total-evaluation/components/nested-list/nested-list.style.ts
  src/features/total-evaluation/components/overall-evaluation/overall-evaluation.styles.ts
  src/features/total-evaluation/components/overall-evaluation/overall-evaluation.tsx
  src/features/total-evaluation/components/project-evaluation/project-evaluation.styles.ts
  src/features/total-evaluation/components/project-evaluation/project-evaluation.tsx
  src/features/total-evaluation/components/summary-title/summary-title.styles.ts
  src/features/total-evaluation/components/summary-title/summary-title.tsx
  src/features/total-evaluation/constants/evaluation-constant.ts
  src/features/total-evaluation/services/use-get-portfolio-feedback.ts
  src/features/total-evaluation/total-evaluation-page.styles.ts
  src/features/total-evaluation/total-evaluation-page.tsx
Labels: 🎨 Style, ✨ Feature

#124 [#120] - 라우팅 타입 수정
  src/app.tsx
  src/common/components/kakao-auth-button/kakao-auth-button.styles.ts
  src/common/components/kakao-auth-button/kakao-auth-button.tsx
  src/common/components/layout/common-layout.styles.ts
  src/common/components/layout/common-layout.tsx
  src/common/components/layout/header-buttons/landing-middle-buttons.styles.ts
  src/common/components/layout/header-buttons/landing-middle-buttons.tsx
  src/common/components/layout/header-buttons/landing-right-buttons.styles.ts
  src/common/components/layout/header-buttons/total-evaluation-left-buttons.styles.ts
  src/common/components/layout/header-buttons/total-evaluation-left-buttons.tsx
  src/common/components/layout/header-navigation/header-navigation-layout.styles.ts
  src/common/components/layout/header-navigation/header-navigation-layout.tsx
  src/common/constants/path.ts
  src/common/hooks/use-heder-contents.tsx
  src/common/utils/generateHederContents.tsx
  src/features/total-evaluation/components/custom-buttons/sidebar-open-button.tsx
  src/features/total-evaluation/components/sidebar/base-sidebar-left/base-sidebar-left.tsx
  src/features/total-evaluation/components/sidebar/feedback-page-navigator/feedback-page-navigator.tsx
  src/features/total-evaluation/total-evaluation-page.tsx
  src/route.tsx
Labels: 🔨 Fix

#122 [#115] - 포트폴리오 히스토리 조회 API 연동
  src/features/profile/common/data.ts
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal.styles.ts
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal.tsx
  src/features/profile/services/use-get-feedback-history.ts
  src/features/profile/util/parse-feedback-data.ts
Labels: ✨ Feature, 🔨 Fix

#126 [#125] - 랜딩페이지 헤더 탭 클릭 시 해당 섹션으로 스크롤 이동
  src/common/components/layout/header-buttons/landing-middle-buttons.tsx
  src/features/landing/components/helpers-section/helpers-section.tsx
  src/features/landing/landing-page.tsx
Labels: ✨ Feature

#134 [#133] - 공통 레이아웃 스크롤 제한 요소 제거
  src/common/components/layout/common-layout.styles.ts
Labels: 🚨 Bug, 🔨 Fix

#132 [#131] - 사이드바 메뉴 이동 로직 적용
  src/common/components/layout/header-buttons/landing-middle-buttons.tsx
  src/common/stories/dummy-data/sidebar.ts
  src/common/stories/sidebar.stories.tsx
  src/common/utils/scroll-to-section.ts
  src/features/total-evaluation/components/accordion-list/feedback-contents.tsx
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.tsx
  src/features/total-evaluation/components/overall-evaluation/overall-evaluation.tsx
  src/features/total-evaluation/components/project-evaluation/project-evaluation.tsx
  src/features/total-evaluation/service/data.ts
  src/features/total-evaluation/total-evaluation-page.tsx
  src/features/total-evaluation/types/sidebar-Info-types.ts
Labels: ✨ Feature

#136 [#128] - 피드백 대기 화면 퍼블리싱 및 반응형 적용
  public/images/grammar.png
  public/images/loading-project-evaluation.png
  public/images/loading-total-evaluation-small.png
  public/images/loading-total-evaluation.png
  public/images/logic.png
  public/images/readability.png
  public/images/redundancy.png
  public/images/translation.png
  src/assets/icons/checkIcon.svg
  src/assets/icons/fix.svg
  src/common/hooks/use-break-point.tsx
  src/common/utils/throttle.ts
  src/features/upload/components/feedback-loading/feedback-loading.styles.ts
  src/features/upload/components/feedback-loading/feedback-loading.tsx
  src/features/upload/components/feedback-loading/loading-evaluation-bottom.styles.ts
  src/features/upload/components/feedback-loading/loading-evaluation-bottom.tsx
  src/features/upload/components/feedback-loading/loading-page-evaluation.styles.ts
  src/features/upload/components/feedback-loading/loading-page-evaluation.tsx
  src/features/upload/components/feedback-loading/loading-project-evaluation.styles.ts
  src/features/upload/components/feedback-loading/loading-project-evaluation.tsx
  src/features/upload/components/feedback-loading/loading-title.styles.ts
  src/features/upload/components/feedback-loading/loading-title.tsx
  src/features/upload/components/feedback-loading/loading-top-section.styles.ts
  src/features/upload/components/feedback-loading/loading-top-section.tsx
  src/features/upload/components/feedback-loading/loading-total-evaluation.styles.ts
  src/features/upload/components/feedback-loading/loading-total-evaluation.tsx
  src/features/upload/constants/loading-constant.ts
  src/features/upload/hooks/useHorizontalScroll.ts
Labels: 🎨 Style, ✨ Feature

#137 [#130] - 랜딩페이지 반응형 적용
  public/images/step-card-01.png
  src/assets/icons/checkIcon.svg
  src/assets/styles/button.ts
  src/assets/styles/device-width.ts
  src/assets/styles/emotion.d.ts
  src/assets/styles/theme.ts
  src/common/hooks/use-device-type.ts
  src/features/landing/common/data.ts
  src/features/landing/components/frequently-asked-questions/frequently-asked-questions.styles.ts
  src/features/landing/components/frequently-asked-questions/frequently-asked-questions.tsx
  src/features/landing/components/helpers-section/detail-improvement.styles.ts
  src/features/landing/components/helpers-section/detail-improvement.tsx
  src/features/landing/components/helpers-section/helpers-section.styles.ts
  src/features/landing/components/helpers-section/helpers-section.tsx
  src/features/landing/components/helpers-section/projects-styles.ts
  src/features/landing/components/helpers-section/projects.tsx
  src/features/landing/components/helpers-section/question-card.styles.ts
  src/features/landing/components/helpers-section/step-card.styles.ts
  src/features/landing/components/helpers-section/total-evaluation-grid.styles.ts
  src/features/landing/components/helpers-section/total-evaluation-grid.tsx
  src/features/landing/components/routing-section/routing-bottom-section.tsx
  src/features/landing/components/routing-section/routing-section.styles.ts
  src/features/landing/components/routing-section/routing-start-section.tsx
  src/features/landing/landing-page.styles.ts
  src/features/landing/landing-page.tsx
Labels: 🎨 Style, ✨ Feature

#141 [#140] - 반응형 Size 수정
  src/assets/styles/device-width.ts
  src/common/hooks/use-device-type.ts
  src/features/upload/components/feedback-loading/loading-page-evaluation.styles.ts
  src/features/upload/components/feedback-loading/loading-page-evaluation.tsx
Labels: 🔨 Fix, 🧤 Refactor

#142 [#127] - 공통 헤더 적용
  src/assets/icons/logo-full-header-desktop.svg
  src/assets/icons/logo-full-header-mobile.svg
  src/common/components/layout/common-layout.tsx
  src/common/components/layout/header-buttons/auth-profile.styles.ts
  src/common/components/layout/header-buttons/auth-profile.tsx
  src/common/components/layout/header-buttons/header-logo.styles.ts
  src/common/components/layout/header-buttons/header-logo.tsx
  src/common/components/layout/header-buttons/landing-middle-buttons.tsx
  src/common/components/layout/header-buttons/landing-right-buttons.styles.ts
  src/common/components/layout/header-buttons/landing/landing-auth-buttons.styles.ts
  src/common/components/layout/header-buttons/landing/landing-auth-buttons.tsx
  src/common/components/layout/header-buttons/landing/landing-scroll-section-buttons.styles.ts
  src/common/components/layout/header-buttons/landing/landing-scroll-section-buttons.tsx
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-auth.styles.ts
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-auth.tsx
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-sidebar-buttons.styles.ts
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-sidebar-buttons.tsx
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-user-info.styles.ts
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-user-info.tsx
  src/common/components/layout/header-navigation/header-navigation-layout.styles.ts
  src/common/components/layout/header-navigation/header-navigation-layout.tsx
  src/common/hooks/use-heder-contents.tsx
  src/common/utils/scroll-to-section.ts
  src/features/total-evaluation/components/accordion-list/accordion-list.tsx
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.tsx
  src/features/total-evaluation/components/sidebar/base-sidebar-left/base-sidebar-left.styles.ts
  src/features/total-evaluation/components/sidebar/base-sidebar-left/base-sidebar-left.tsx
  src/features/total-evaluation/components/sidebar/feedback-page-navigator/control-buttons.tsx
  src/features/upload/components/file-upload/file-upload.styles.ts
Labels: ✨ Feature, 🔨 Fix

#143 [#139] - 랜딩 페이지 인터랙션 적용
  package.json
  pnpm-lock.yaml
  src/common/components/interaction/fade-in-div.styles.ts
  src/common/components/interaction/fade-in-div.tsx
  src/features/landing/components/frequently-asked-questions/frequently-asked-questions.styles.ts
  src/features/landing/components/frequently-asked-questions/frequently-asked-questions.tsx
  src/features/landing/components/helpers-section/detail-improvement.styles.ts
  src/features/landing/components/helpers-section/detail-improvement.tsx
  src/features/landing/components/helpers-section/helpers-section.tsx
  src/features/landing/components/helpers-section/question-card.tsx
  src/features/landing/components/helpers-section/step-card.styles.ts
  src/features/landing/components/helpers-section/step-card.tsx
  src/features/landing/components/routing-section/routing-bottom-section.tsx
  src/features/landing/components/routing-section/routing-section.styles.ts
  src/features/landing/landing-page.styles.ts
  src/features/landing/landing-page.tsx
Labels: 🎨 Style

#145 [#144] - 헤더 스크롤 인터렉션 좌표 수정
  src/common/utils/scroll-to-section.ts
Labels: 🚨 Bug, 🔨 Fix

#149 [#148] - 전체 페이지 푸터 적용
  src/assets/icons/behance-logo.svg
  src/common/components/layout/common-layout.tsx
  src/common/components/layout/footer/footer.styles.ts
  src/common/components/layout/footer/footer.tsx
Labels: 🎨 Style

#147 [#123] - 장표별 피드백 api 연동 및 피드백 로딩 페이지 로직 수정
  src/assets/styles/device-width.ts
  src/common/constants/path.ts
  src/common/hooks/use-break-point.tsx
  src/common/stories/dummy-data/sidebar.ts
  src/features/total-evaluation/components/improvement-section/improvement-section.tsx
  src/features/total-evaluation/components/improvement-title/improvement-title.tsx
  src/features/total-evaluation/components/logical-leap/logical-error.styles.ts
  src/features/total-evaluation/components/logical-leap/logical-error.tsx
  src/features/total-evaluation/components/logical-leap/logical-improvement.styles.ts
  src/features/total-evaluation/components/logical-leap/logical-improvement.tsx
  src/features/total-evaluation/components/logical-leap/logical-leap-content.styles.ts
  src/features/total-evaluation/components/logical-leap/logical-leap-content.tsx
  src/features/total-evaluation/components/logical-leap/logical-leap.styles.ts
  src/features/total-evaluation/components/logical-leap/logical-leap.tsx
  src/features/total-evaluation/components/project-evaluation/project-evaluation.styles.ts
  src/features/total-evaluation/components/project-evaluation/project-evaluation.tsx
  src/features/total-evaluation/components/summary-title/summary-title.tsx
  src/features/total-evaluation/constants/evaluation-constant.ts
  src/features/total-evaluation/services/use-get-portfolio-feedback.ts
  src/features/total-evaluation/total-evaluation-page.tsx
  src/features/upload/components/feedback-loading/feedback-loading.styles.ts
  src/features/upload/components/feedback-loading/loading-evaluation-bottom.styles.ts
  src/features/upload/components/feedback-loading/loading-evaluation-bottom.tsx
  src/features/upload/components/feedback-loading/loading-page-evaluation.styles.ts
  src/features/upload/components/feedback-loading/loading-page-evaluation.tsx
  src/features/upload/components/feedback-loading/loading-project-evaluation.styles.ts
  src/features/upload/components/feedback-loading/loading-project-evaluation.tsx
  src/features/upload/components/feedback-loading/loading-title.styles.ts
  src/features/upload/components/feedback-loading/loading-title.tsx
  src/features/upload/components/feedback-loading/loading-top-section.tsx
  src/features/upload/components/feedback-loading/loading-total-evaluation.styles.ts
  src/features/upload/components/feedback-loading/loading-total-evaluation.tsx
  src/features/upload/hooks/useHorizontalScroll.ts
  src/route.tsx
Labels: 🔨 Fix, 🧤 Refactor

#153 [#151] - 경로 수정, Header 오류 수정, 포트폴리오 피드백 인터렉션 일부 적용
  src/common/components/layout/header-navigation/header-navigation-layout.styles.ts
  src/common/components/layout/header-navigation/header-navigation-layout.tsx
  src/common/hooks/use-header-contents.tsx
  src/features/upload/components/feedback-loading/loading-project-evaluation.tsx
  src/features/upload/components/feedback-loading/loading-title.tsx
  src/features/upload/components/feedback-loading/loading-top-section.styles.ts
  src/features/upload/components/feedback-loading/loading-top-section.tsx
  src/features/upload/components/feedback-loading/loading-total-evaluation.tsx
  src/features/upload/constants/loading-constant.ts
Labels: 🚨 Bug, 🔨 Fix

#159 [#154] - 가로 스크롤 그림자 스타일 적용
  src/common/hooks/use-shadow-scroll.tsx
  src/features/feedback-history/services/use-get-feedback-history.ts
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal.styles.ts
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal.tsx
  src/features/total-evaluation/components/project-evaluation/project-evaluation.tsx
  src/features/upload/components/feedback-loading/loading-page-evaluation.styles.ts
  src/features/upload/components/feedback-loading/loading-page-evaluation.tsx
  src/features/upload/components/feedback-loading/loading-top-section.tsx
  src/features/upload/constants/loading-constant.ts
  src/features/upload/upload-page.tsx
Labels: 🔨 Fix, 🧤 Refactor

#169 [#168] - Icon 타입을 위한 icon 파일 이름 파싱기능 구현
  package.json
  pnpm-lock.yaml
  script/generate-icon-types.ts
  src/assets/styles/button.ts
  src/common/components/icon/icon.tsx
  src/common/components/toast/toast-config.ts
  src/common/types/icon-types.ts
  src/features/total-evaluation/components/overall-evaluation/overall-evaluation.tsx
  src/features/total-evaluation/components/project-evaluation/project-evaluation.tsx
Labels: ⚙️ Chore, 🧤 Refactor

#162 [#158] - 포트폴리오 피드백 조회 Suspense 적용 및 오류 처리 개선
  package.json
  pnpm-lock.yaml
  src/common/components/fallback-boundary/fallback-boundary.tsx
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-user-info.tsx
  src/common/components/skeleton/skeleton.styles.ts
  src/common/components/skeleton/skeleton.tsx
  src/common/components/toast/toast-config.ts
  src/common/components/toast/toast.styles.ts
  src/common/stories/sidebar.stories.tsx
  src/features/total-evaluation/components/accordion-list/feedback-contents.tsx
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.tsx
  src/features/total-evaluation/components/overall-evaluation/overall-evaluation.tsx
  src/features/total-evaluation/components/project-evaluation/project-evaluation-list.tsx
  src/features/total-evaluation/hooks/use-get-portfolio-feedback-data.ts
  src/features/total-evaluation/services/use-get-portfolio-feedback.ts
  src/features/total-evaluation/total-evaluation-page.styles.ts
  src/features/total-evaluation/total-evaluation-page.tsx
Labels: ✨ Feature, 🧤 Refactor

#172 [#171] - Icon type 관련 버그 수정
  src/common/components/toast/toast-config.ts
  src/common/types/icon-types.ts
  src/features/total-evaluation/components/evaluation-chart/evaluation-chart.tsx
  src/features/upload/components/feedback-loading/loading-evaluation-bottom.tsx
Labels: 🚨 Bug

#166 [#160] - 피드백 로딩 페이지 인터렉션 적용
  src/features/upload/components/feedback-loading/loading-evaluation-bottom.tsx
  src/features/upload/components/feedback-loading/loading-page-evaluation.tsx
  src/features/upload/components/feedback-loading/loading-project-evaluation.tsx
  src/features/upload/components/feedback-loading/loading-title.styles.ts
  src/features/upload/components/feedback-loading/loading-title.tsx
  src/features/upload/components/feedback-loading/loading-top-section.styles.ts
  src/features/upload/components/feedback-loading/loading-top-section.tsx
  src/features/upload/components/feedback-loading/loading-total-evaluation.tsx
Labels: 🎨 Style, 🧤 Refactor

#173 [#150] - 랜딩 페이지 디자인 QA 반영
  src/features/landing/components/frequently-asked-questions/frequently-asked-questions.styles.ts
  src/features/landing/components/frequently-asked-questions/frequently-asked-questions.tsx
  src/features/landing/components/helpers-section/detail-improvement.styles.ts
  src/features/landing/components/helpers-section/detail-improvement.tsx
  src/features/landing/landing-page.styles.ts
  src/features/landing/landing-page.tsx
Labels: 🎨 Style

#181 [#180] - 사이드바 상태에 따른 푸터 너비 조절
  src/common/components/layout/footer/footer.tsx
Labels: 🎨 Style, 🔨 Fix

#177 [#119] - 개발 환경 로그인 연동
  .gitignore
  package.json
  pnpm-lock.yaml
  src/common/components/auth/Authorization.tsx
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-sidebar-buttons.tsx
  src/common/components/layout/header-navigation/header-navigation-layout.tsx
  src/common/hooks/use-check-query-strings.ts
  src/common/services/auth.ts
  src/common/services/service-config.ts
  src/common/types/auth.ts
  src/features/login/components/custom-buttons/google-auth-button.tsx
  src/features/login/login-page.tsx
  src/features/total-evaluation/components/context/selected-page/selected-page-context.tsx
  src/features/total-evaluation/components/context/selected-page/use-selected-page-context.tsx
  src/features/total-evaluation/components/context/sidebar/sidebar-context.tsx
  src/features/total-evaluation/components/context/sidebar/use-sidebar-context.tsx
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.tsx
  src/features/total-evaluation/components/sidebar/feedback-page-navigator/feedback-page-navigator.tsx
  src/features/upload/upload-page.tsx
  src/route.tsx
  src/store/user-auth.ts
  vite.config.ts
Labels: ⚙️ Chore, 🌏 Deploy, ✨ Feature

#183 [#182] - 사이드바 context 타입 및 import 수정
  src/common/components/layout/footer/footer.tsx
Labels: 🚨 Bug, 🔨 Fix

#184 [#176] - 포트폴리오 피드백 조회 로딩 및 에러 UI 반영
  src/assets/icons/loading.svg
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-user-info.tsx
  src/common/components/skeleton/skeleton.styles.ts
  src/common/components/skeleton/skeleton.tsx
  src/common/components/toast/toast-config.ts
  src/common/components/toast/toast.styles.ts
  src/common/types/icon-types.ts
  src/features/feedback/services/use-get-portfolio-feedback.ts
  src/features/total-evaluation/components/fallback-ui/fallback-ui.styles.ts
  src/features/total-evaluation/components/fallback-ui/sidebar-fallback-ui.tsx
  src/features/total-evaluation/components/fallback-ui/total-evaluation-fallback-ui.tsx
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.tsx
  src/features/total-evaluation/total-evaluation-page.styles.ts
  src/features/total-evaluation/total-evaluation-page.tsx
Labels: 🎨 Style

#185 [#175] - 히스토리 조회 모달 에러 UI 반영, 디자인 QA 반영
  src/common/components/modal/base-modal.styles.ts
  src/common/components/toast/toast-config.tsx
  src/common/components/toast/toast.tsx
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal.styles.ts
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal.tsx
  src/features/upload/components/feedback-loading/loading-page-evaluation.styles.ts
  src/features/upload/components/feedback-loading/loading-top-section.tsx
Labels: 🎨 Style, 🧤 Refactor

#187 [#186] - 피드백 헤더 메타 데이터 추가
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-user-info.tsx
  src/features/feedback/services/use-get-portfolio-feedback.ts
  src/features/total-evaluation/utils/adapt-accordion-format.ts
  src/features/total-evaluation/utils/convert-kr-date.ts
Labels: ✨ Feature

#191 [#190] - 랜딩 페이지 세부 개선점 shadow 수정
  src/features/landing/components/helpers-section/detail-improvement.styles.ts
Labels: 🎨 Style

#189 [#188] - 포트폴리오 피드백 조회 에러 시 토스트 아이콘 수정
  src/common/components/toast/toast-config.tsx
  src/features/total-evaluation/total-evaluation-page.styles.ts
  src/features/total-evaluation/total-evaluation-page.tsx
Labels: 🎨 Style

#179 [#161] - 피드백 페이지 프로필 모달 생성
  package.json
  pnpm-lock.yaml
  src/common/components/global-route-config/global-route-config.tsx
  src/common/components/layout/header-buttons/auth-profile-modal-dropdown.styles.ts
  src/common/components/layout/header-buttons/auth-profile-modal-dropdown.tsx
  src/common/components/layout/header-buttons/auth-profile.styles.ts
  src/common/components/layout/header-buttons/auth-profile.tsx
  src/common/components/layout/header-buttons/total-evaluation/single-profile-modal-button.styles.ts
  src/common/components/layout/header-buttons/total-evaluation/single-profile-modal-button.tsx
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-auth.styles.ts
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-auth.tsx
  src/common/components/layout/header-navigation/header-navigation-layout.styles.ts
  src/common/hooks/use-header-contents.tsx
  src/features/login/login-page.tsx
  src/features/total-evaluation/components/sidebar/base-sidebar-left/base-sidebar-left.styles.ts
  src/features/total-evaluation/total-evaluation-page.tsx
Labels: ✨ Feature
