Repository depromeet/16th-team1-FE, pull requests merged in 2025-02, with the labels that each got.

#3 [#2] - 커밋 메시지 검증 스크립트 수정
  .husky/commit-msg
Labels: ⚙️ Chore

#4 [#1] - Storybook 설정 및 배포
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  script/publish_chromatic.sh
  src/components/progress-bar/index.tsx
  src/stories/Configure.mdx
  src/stories/ProgressBar.stories.tsx
Labels: ⚙️ Chore

#6 chore #5 : CI 세팅
  .github/WORKFLOWS/deploy.yml
Labels: ⚙️ Chore

#7 2/8
  .github/WORKFLOWS/deploy.yml
Labels: ⚙️ Chore

#8 chore #5 : CI 세팅
  .github/workflows/deploy.yml
Labels: ⚙️ Chore

#9 chore #5 : CI 세팅
  .github/workflows/deploy.yml
Labels: ⚙️ Chore

#10 chore #5 : CI 세팅 fix
  .github/workflows/deploy.yml
Labels: ⚙️ Chore

#11 chore #5 : CI 세팅 fix
  .github/workflows/deploy.yml
Labels: ⚙️ Chore

#12 chore #5 : CI 세팅 fix
  .github/workflows/deploy.yml
Labels: ⚙️ Chore

#13 chore #5 : CI 세팅 fix
  .github/workflows/deploy.yml
Labels: ⚙️ Chore

#14 Chore ci setting
  .github/workflows/deploy.yml
Labels: ⚙️ Chore

#17 [#16] - PR 머지 시 관련 이슈 자동 종료되도록 템플릿 수정
  .github/pull_request_template.md
Labels: ⚙️ Chore

#19 [#18] - Emotion관련 eslint rule추가 및 스타일 기본 파일명 변경
  eslint.config.js
  src/App.styles.ts
  src/App.tsx
Labels: ⚙️ Chore

#23 [#22] - Storybook CI/CD 파이프라인 구축
  .github/workflows/chromatic.yml
  src/stories/ProgressBar.stories.tsx
Labels: ⚙️ Chore

#26 [#24] - Button 공통 컴포넌트 생성
  .gitconfig
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/common/components/basebutton/BaseButton.styles.ts
  src/common/components/basebutton/index.tsx
  src/common/components/button/Button.styles.ts
  src/common/components/button/index.tsx
  src/common/components/kakaoauthbutton/KakaoAuthButton.styles.ts
  src/common/components/kakaoauthbutton/index.tsx
  src/common/components/progress-bar/index.tsx
  src/common/components/test-component/index.tsx
  src/common/hooks/use-toggle.tsx
  src/common/stories/Configure.mdx
  src/common/stories/ProgressBar.stories.tsx
  src/common/test/sum.test.ts
  src/common/test/test-component.test.tsx
  src/common/test/use-toggle.test.tsx
  src/main.tsx
Labels: ✨ Feature

#28 [#27] - Storybook CI/CD 트리거 조건 수정
  .github/workflows/chromatic.yml
  src/common/stories/ProgressBar.stories.tsx
Labels: ⚙️ Chore

#32 [#31] - Reset CSS 적용 및 기본 단위 rem으로 설정
  src/App.tsx
  src/styles/globalStyles.ts
Labels: ⚙️ Chore

#37 [#36] - 파일명 Kebab case 규칙 적용
  src/app.styles.ts
  src/app.tsx
  src/common/components/bar-chart/bar-chart.styles.ts
  src/common/components/bar-chart/index.tsx
  src/common/components/base-button/base-button.styles.ts
  src/common/components/base-button/index.tsx
  src/common/components/button/button.styles.ts
  src/common/components/button/index.tsx
  src/common/components/kakao-auth-button/index.tsx
  src/common/components/kakao-auth-button/kakao-auth-button.styles.ts
  src/common/stories/bar-chart.stories.tsx
  src/common/stories/configure.mdx
  src/common/stories/progress-bar.stories.tsx
  src/features/total-evaluation/components/evaluation-chart.styles.ts
  src/features/total-evaluation/components/evaluation-chart.tsx
  src/features/total-evaluation/components/evaluation-summary.styles.ts
  src/features/total-evaluation/components/evaluation-summary.tsx
  src/features/total-evaluation/components/evaluation-table.styles.ts
  src/features/total-evaluation/components/evaluation-table.tsx
  src/features/total-evaluation/config/evaluation-config.ts
  src/features/total-evaluation/index.tsx
  src/features/total-evaluation/types/evaluation-types.ts
  src/features/total-evaluation/utils/get-evaluation-data.ts
  src/main.tsx
  src/styles/global-styles.ts
Labels: 🔨 Fix

#38 [#34] - 사이드바 초기 마크업 생성 및 기존 파일 컨벤션 수정
  package.json
  pnpm-lock.yaml
  src/app.styles.ts
  src/app.tsx
  src/common/components/bar-chart/bar-chart.tsx
  src/common/components/base-button/base-button.styles.ts
  src/common/components/base-button/base-button.tsx
  src/common/components/button/Button.tsx
  src/common/components/kakao-auth-button/kakao-auth-button.styles.ts
  src/common/components/kakao-auth-button/kakao-auth-button.tsx
  src/common/components/progress-bar/progress-bar.tsx
  src/common/components/test-component/test-component.tsx
  src/common/stories/bar-chart.stories.tsx
  src/common/stories/progress-bar.stories.tsx
  src/common/test/test-component.test.tsx
  src/features/total-evaluation/components/accordion-menu/accordion-menu.styles.ts
  src/features/total-evaluation/components/accordion-menu/accordion-menu.tsx
  src/features/total-evaluation/components/evaluation-chart.tsx
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.styles.ts
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.tsx
  src/features/total-evaluation/components/left-slide-panel-toggle/left-slide-panel-toggle.styles.ts
  src/features/total-evaluation/components/left-slide-panel-toggle/left-slide-panel-toggle.tsx
  src/features/total-evaluation/components/menu-buttons/menu-trigger-button.styles.ts
  src/features/total-evaluation/components/menu-buttons/menu-trigger-button.tsx
  src/features/total-evaluation/components/menu-buttons/single-menu-button.styles.ts
  src/features/total-evaluation/components/menu-buttons/single-menu-button.tsx
  src/features/total-evaluation/index.styles.ts
  src/features/total-evaluation/index.tsx
  src/features/total-evaluation/service/data.ts
  src/features/total-evaluation/total-evaluation-page.styles.ts
  src/features/total-evaluation/total-evaluation-page.tsx
  src/features/total-evaluation/types/sidebar-Info-types.ts
  src/features/total-evaluation/utils/adapt-accordion-format.ts
Labels: ✨ Feature

#39 [#35] - 포트폴리오 피드백 강점 분석 및 해결방안 섹션 퍼블리싱
  src/features/total-evaluation/common/data.ts
  src/features/total-evaluation/components/evaluation-analyze.styles.ts
  src/features/total-evaluation/components/evaluation-analyze.tsx
  src/features/total-evaluation/components/evaluation-title.tsx
  src/features/total-evaluation/components/evaluation.title.styles.ts
  src/features/total-evaluation/total-evaluation-page.tsx
Labels: 🎨 Style

#47 [#46] - global style 수정
  src/styles/global-styles.ts
Labels: 🔨 Fix

#44 [#25] - 문장 개선 섹션 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/assets/icons/checkIcon.svg
  src/features/total-evaluation/common/data.ts
  src/features/total-evaluation/components/improvement-section/improvement-section.styles.ts
  src/features/total-evaluation/components/improvement-section/improvement-section.tsx
  src/features/total-evaluation/components/improvement-section/improvement-text.styles.ts
  src/features/total-evaluation/components/improvement-section/improvement-text.tsx
  src/features/total-evaluation/components/improvement-section/improvement-title.styles.ts
  src/features/total-evaluation/components/improvement-section/improvement-title.tsx
  src/features/total-evaluation/constant/evaluation-constant.ts
  src/features/total-evaluation/total-evaluation-page.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: 🎨 Style

#48 [#41] - 포트폴리오 피드백 항목별 설명 리스트 퍼블리싱
  src/common/components/bar-chart/bar-chart.styles.ts
  src/common/components/button/button.styles.ts
  src/common/components/kakao-auth-button/kakao-auth-button.styles.ts
  src/common/components/progress-bar/progress-bar.tsx
  src/features/total-evaluation/common/data.ts
  src/features/total-evaluation/components/accordion-menu/accordion-menu.styles.ts
  src/features/total-evaluation/components/evaluation-analyze.tsx
  src/features/total-evaluation/components/evaluation-analyze/evaluation-analyze.styles.ts
  src/features/total-evaluation/components/evaluation-analyze/evaluation-analyze.tsx
  src/features/total-evaluation/components/evaluation-chart/evaluation-chart.styles.ts
  src/features/total-evaluation/components/evaluation-chart/evaluation-chart.tsx
  src/features/total-evaluation/components/evaluation-summary/evaluation-summary.styles.ts
  src/features/total-evaluation/components/evaluation-summary/evaluation-summary.tsx
  src/features/total-evaluation/components/evaluation-table/evaluation-table.styles.ts
  src/features/total-evaluation/components/evaluation-table/evaluation-table.tsx
  src/features/total-evaluation/components/evaluation-title/evaluation-title.styles.ts
  src/features/total-evaluation/components/evaluation-title/evaluation-title.tsx
  src/features/total-evaluation/components/improvement-section/improvement-section.tsx
  src/features/total-evaluation/components/left-slide-panel-toggle/left-slide-panel-toggle.styles.ts
  src/features/total-evaluation/components/nested-list/nested-list.style.ts
  src/features/total-evaluation/components/nested-list/nested-list.tsx
  src/features/total-evaluation/config/evaluation-config.ts
  src/features/total-evaluation/constant/evaluation-constant.ts
  src/features/total-evaluation/constants/evaluation-constant.ts
  src/features/total-evaluation/total-evaluation-page.styles.ts
  src/features/total-evaluation/total-evaluation-page.tsx
  src/features/total-evaluation/utils/get-evaluation-data.ts
Labels: 🎨 Style

#50 [#45] - 논리적 비약 섹션 퍼블리싱
  src/assets/icons/greenPin.svg
  src/assets/icons/redPin.svg
  src/features/total-evaluation/common/data.ts
  src/features/total-evaluation/components/improvement-section/improvement-section.styles.ts
  src/features/total-evaluation/components/improvement-section/improvement-section.tsx
  src/features/total-evaluation/components/improvement-title/improvement-title.styles.ts
  src/features/total-evaluation/components/improvement-title/improvement-title.tsx
  src/features/total-evaluation/components/logical-leap/logical-error.styles.ts
  src/features/total-evaluation/components/logical-leap/logical-error.tsx
  src/features/total-evaluation/components/logical-leap/logical-improvement.styles.ts
  src/features/total-evaluation/components/logical-leap/logical-improvement.tsx
  src/features/total-evaluation/components/logical-leap/logical-leap.styles.ts
  src/features/total-evaluation/components/logical-leap/logical-leap.tsx
  src/features/total-evaluation/constants/evaluation-constant.ts
  src/features/total-evaluation/total-evaluation-page.tsx
Labels: 🎨 Style, 🧤 Refactor

#49 [#40] - 사이드바 로직 개선 및 세부 마크업 진행
  package.json
  pnpm-lock.yaml
  src/common/components/base-button/base-button.styles.ts
  src/features/total-evaluation/components/accordion-list/accordion-list.tsx
  src/features/total-evaluation/components/accordion-list/single-accordion-item.styles.ts
  src/features/total-evaluation/components/accordion-list/single-accordion-item.tsx
  src/features/total-evaluation/components/accordion-menu/accordion-menu.styles.ts
  src/features/total-evaluation/components/accordion-menu/accordion-menu.tsx
  src/features/total-evaluation/components/custom-buttons/accordion-trigger-button.styles.ts
  src/features/total-evaluation/components/custom-buttons/accordion-trigger-button.tsx
  src/features/total-evaluation/components/custom-buttons/single-content-button.styles.ts
  src/features/total-evaluation/components/custom-buttons/single-content-button.tsx
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.styles.ts
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.tsx
  src/features/total-evaluation/components/left-slide-panel-toggle/left-slide-panel-toggle.styles.ts
  src/features/total-evaluation/components/left-slide-panel-toggle/left-slide-panel-toggle.tsx
  src/features/total-evaluation/components/menu-buttons/menu-trigger-button.styles.ts
  src/features/total-evaluation/components/menu-buttons/menu-trigger-button.tsx
  src/features/total-evaluation/components/menu-buttons/single-menu-button.tsx
  src/features/total-evaluation/total-evaluation-page.styles.ts
  src/features/total-evaluation/total-evaluation-page.tsx
  src/features/total-evaluation/utils/adapt-accordion-format.ts
Labels: ✨ Feature, 🧤 Refactor

#54 [#53] - import 경로 alias 설정
  package.json
  pnpm-lock.yaml
  src/app.tsx
  src/assets/styles/global-styles.ts
  src/common/components/button/Button.tsx
  src/common/components/kakao-auth-button/kakao-auth-button.tsx
  src/common/stories/bar-chart.stories.tsx
  src/common/stories/progress-bar.stories.tsx
  src/common/test/test-component.test.tsx
  src/common/test/use-toggle.test.tsx
  src/features/total-evaluation/components/accordion-list/accordion-list.tsx
  src/features/total-evaluation/components/custom-buttons/accordion-trigger-button.styles.ts
  src/features/total-evaluation/components/custom-buttons/accordion-trigger-button.tsx
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.tsx
  src/features/total-evaluation/components/improvement-section/improvement-section.tsx
  src/features/total-evaluation/components/improvement-title/improvement-title.tsx
  src/features/total-evaluation/components/logical-leap/logical-error.tsx
  src/features/total-evaluation/components/logical-leap/logical-improvement.tsx
  src/features/total-evaluation/components/logical-leap/logical-leap.tsx
  src/features/total-evaluation/constants/evaluation-constant.ts
  src/features/total-evaluation/total-evaluation-page.tsx
  src/features/upload/components/file-upload/file-upload.tsx
  src/features/upload/stories/file-upload.stories.tsx
  src/features/upload/upload-page.tsx
  src/route.tsx
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ⚙️ Chore

#61 [#59] - 기본 폰트 및 타이포그래피 설정
  index.html
  src/app.tsx
  src/assets/styles/emotion.d.ts
  src/assets/styles/fonts.ts
  src/assets/styles/global-styles.ts
  src/assets/styles/theme.ts
  src/common/utils/with-theme.ts
Labels: 🎨 Style

#62 [#55] - Icon 공통 컴포넌트
  src/assets/icons/greenPin.svg
  src/assets/icons/pin.svg
  src/common/components/icon/icon-map.ts
  src/common/components/icon/icon.tsx
  src/common/components/icon/iconPalette.json
  src/common/stories/icon.stories.tsx
  src/features/total-evaluation/components/improvement-title/improvement-title.tsx
  src/features/total-evaluation/components/logical-leap/logical-error.tsx
  src/features/total-evaluation/components/logical-leap/logical-improvement.tsx
Labels: ✨ Feature, 🔨 Fix

#64 [#63] - Colorsystem 설정
  src/assets/styles/colors.ts
  src/assets/styles/emotion.d.ts
  src/assets/styles/theme.ts
Labels: 🎨 Style

#69 [#67] - 버튼 공통 컴포넌트 디자인 시스템 적용
  .stylelintrc.json
  src/assets/styles/button.ts
  src/assets/styles/emotion.d.ts
  src/assets/styles/space.ts
  src/assets/styles/theme.ts
  src/common/components/button/Button.tsx
  src/common/components/button/base-button.styles.ts
  src/common/components/button/base-button.tsx
  src/common/components/button/button.stories.tsx
  src/common/components/button/button.styles.ts
  src/common/components/kakao-auth-button/kakao-auth-button.tsx
  src/features/total-evaluation/components/custom-buttons/accordion-trigger-button.tsx
  src/features/total-evaluation/components/custom-buttons/sidebar-close-button.tsx
  src/features/total-evaluation/components/custom-buttons/sidebar-open-button.tsx
  src/features/total-evaluation/components/custom-buttons/single-content-button.tsx
  src/features/upload/components/file-upload/file-upload.tsx
Labels: ✨ Feature

#72 [#71] - Colorsystem 추가
  src/assets/styles/colors.ts
Labels: 🎨 Style

#73 [#66] - Toast 공통 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/assets/icons/loginFail.svg
  src/assets/icons/pdfSubmitSuccess.svg
  src/assets/icons/rightArrow.svg
  src/assets/icons/upArrow.svg
  src/common/components/icon/icon.tsx
  src/common/components/icon/iconPalette.json
  src/common/components/toast/toast-config.ts
  src/common/components/toast/toast.styles.ts
  src/common/components/toast/toast.tsx
  src/common/stories/ toast.stories.tsx
  src/common/stories/icon.stories.tsx
  src/features/total-evaluation/components/logical-leap/logical-improvement.tsx
Labels: ✨ Feature, 🔨 Fix
