Repository depromeet/16th-team1-FE, pull requests merged in 2025-04, with the labels that each got.

#199 [#194] - 히스토리 조회 모달 로직 수정
  src/features/feedback/services/use-get-feedback-history.ts
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal-content.styles.ts
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal-content.tsx
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal.tsx
  src/features/upload/components/upload/upload.tsx
Labels: 🔨 Fix, 🧤 Refactor

#201 [#198] - 값이 없을 경우 '-'을 반환하는 유틸 함수 구현
  src/common/components/layout/header-buttons/auth-profile-modal-dropdown.tsx
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-user-info.tsx
  src/common/utils/get-value-or-hyphen.ts
  src/features/feedback/services/use-get-portfolio-feedback.ts
  src/features/total-evaluation/components/accordion-list/feedback-contents.tsx
  src/features/total-evaluation/components/nested-list/nested-list.tsx
  src/features/total-evaluation/components/overall-evaluation/overall-evaluation.tsx
  src/features/total-evaluation/components/project-evaluation/project-evaluation-list.tsx
  src/features/upload/components/file-upload/file-upload.tsx
Labels: 🧤 Refactor

#202 [#197] - 푸터 레이아웃 수정
  package.json
  pnpm-lock.yaml
  src/common/components/interaction/fade-in-div.styles.ts
  src/common/components/interaction/fade-in-div.tsx
  src/common/components/layout/footer/footer.styles.ts
  src/common/components/layout/footer/footer.tsx
  src/common/components/progress-bar/progress-bar.tsx
  src/common/constants/layout.ts
  src/common/stories/progress-bar.stories.tsx
  src/features/login/login-page.styles.ts
  src/features/total-evaluation/total-evaluation-page.styles.ts
  src/features/upload/components/upload/upload.styles.ts
Labels: 🎨 Style

#205 [#204] - CDN 폰트 → 로컬 WOFF2로 변경
  index.html
  src/assets/fonts/PretendardVariable.woff2
  src/assets/styles/global-styles.ts
Labels: 🧤 Refactor

#203 [#192] - 로그인 싸이클 버그 수정
  src/auth-timer.ts
  src/common/components/auth/Authorization.tsx
  src/common/components/global-route-config/global-route-config.tsx
  src/common/components/layout/header-buttons/auth-profile-modal-dropdown.tsx
  src/common/components/layout/header-buttons/auth-profile.tsx
  src/common/components/layout/header-buttons/landing/landing-auth-buttons.styles.ts
  src/common/components/layout/header-buttons/landing/landing-auth-buttons.tsx
  src/common/components/layout/header-navigation/header-navigation-layout.tsx
  src/common/error/custom-auth-error.ts
  src/common/hooks/use-auth-cycle.ts
  src/common/services/auth-builder.ts
  src/common/services/auth.ts
  src/common/services/service-config.ts
  src/features/feedback/services/use-get-portfolio-feedback.ts
  src/features/landing/landing-page.tsx
  src/features/login/login-page.tsx
  src/features/upload/components/upload/upload.tsx
  src/store/user-auth.ts
Labels: 🚨 Bug, ✨ Feature, 🔨 Fix

#211 [#210] - vars -> secrets로 변경
  .github/workflows/deploy.yml
Labels: 🧤 Refactor

#214 [#213] - FallbackBoundary reset 시 Query 상태도 초기화되도록 개선
  src/common/components/fallback-boundary/fallback-boundary.tsx
  src/features/feedback/services/use-get-portfolio-feedback.ts
Labels: 🧤 Refactor

#222 favicon 설정 및 레이아웃 버그 수정
  index.html
  public/favicon/android-icon-144x144.png
  public/favicon/android-icon-192x192.png
  public/favicon/android-icon-36x36.png
  public/favicon/android-icon-48x48.png
  public/favicon/android-icon-72x72.png
  public/favicon/android-icon-96x96.png
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/apple-icon-precomposed.png
  public/favicon/apple-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/manifest.json
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
  src/common/components/fallback-boundary/fallback-boundary.tsx
  src/common/components/layout/common-layout.styles.ts
  src/common/components/layout/common-layout.tsx
  src/common/components/layout/footer/footer.styles.ts
  src/common/constants/layout.ts
  src/features/feedback/services/use-get-portfolio-feedback.ts
  src/features/landing/components/helpers-section/projects-wrapper.tsx
  src/features/landing/components/helpers-section/total-evaluation-grid.styles.ts
  src/features/login/login-page.styles.ts
  src/features/total-evaluation/total-evaluation-page.styles.ts
  src/features/upload/components/upload/upload.styles.ts
Labels: 🧤 Refactor

#227 [#225] - 헤더 로직 추가
  src/common/components/layout/header-buttons/header-logo.tsx
  src/common/components/layout/header-buttons/landing/landing-auth-buttons.tsx
  src/common/components/layout/header-buttons/profile-dropdown.styles.ts
  src/common/components/layout/header-buttons/profile-dropdown.tsx
  src/common/components/layout/header-buttons/profile-menu.tsx
  src/common/components/layout/header-buttons/total-evaluation/single-profile-modal-button.styles.ts
  src/common/components/layout/header-buttons/total-evaluation/single-profile-modal-button.tsx
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-sidebar-buttons.tsx
  src/common/hooks/use-header-contents.tsx
Labels: ✨ Feature

#208 [#200] - 피드백 로딩중일때 각 상태에 따른 Toast 표시
  src/assets/icons/spinner.svg
  src/common/components/feedback-state-observer/feedback-state-observer.tsx
  src/common/components/global-route-config/global-route-config.tsx
  src/common/components/toast/toast-config.tsx
  src/common/components/toast/toast.styles.ts
  src/common/hooks/use-toast.ts
  src/common/stories/toast.stories.tsx
  src/common/types/icon-types.ts
  src/store/feedback.ts
Labels: ✨ Feature, 🧤 Refactor

#230 [#229] - 더미 프로필 추가, 사이드바 텍스트 초과 처리
  src/common/components/layout/header-buttons/auth-profile.styles.ts
  src/common/components/layout/header-buttons/auth-profile.tsx
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.styles.ts
  src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.tsx
Labels: ✨ Feature

#234 [#232] - 랜딩페이지 및 포트폴리오 피드백 조회 QA 반영
  src/common/components/layout/footer/footer.styles.ts
  src/common/components/layout/footer/footer.tsx
  src/features/total-evaluation/components/evaluation-table/evaluation-table.styles.ts
  src/features/total-evaluation/components/overall-evaluation/overall-evaluation.tsx
  src/features/total-evaluation/components/project-evaluation/project-evaluation.tsx
  src/features/upload/components/upload/upload.tsx
Labels: 🔨 Fix

#235 Feat 404page
  src/assets/icons/not-found.svg
  src/common/components/not-found-page/not-found-page.styles.ts
  src/common/components/not-found-page/not-found-page.tsx
  src/common/types/icon-types.ts
  src/route.tsx
Labels: 🎨 Style, ✨ Feature

#239 [#238] - 포트폴리오 피드백 조회 응답값 수정
  src/common/components/layout/footer/footer.styles.ts
  src/common/components/layout/footer/footer.tsx
  src/common/stories/dummy-data/sidebar.ts
  src/features/feedback/services/use-get-portfolio-feedback.ts
  src/features/total-evaluation/components/project-evaluation/project-evaluation.tsx
Labels: 🔨 Fix

#237 [#233] - QA: 헤더, 사이드바, 랜딩 페이지
  src/common/components/layout/header-buttons/profile-dropdown.styles.ts
  src/common/components/layout/header-buttons/total-evaluation/single-profile-modal-button.styles.ts
  src/common/components/layout/header-navigation/header-navigation-layout.styles.ts
  src/features/landing/components/helpers-section/total-evaluation-grid.styles.ts
  src/features/total-evaluation/components/custom-buttons/add-button.tsx
  src/features/total-evaluation/components/sidebar/base-sidebar-left/base-sidebar-left.styles.ts
  src/features/total-evaluation/components/sidebar/feedback-page-navigator/control-buttons.styles.ts
  src/features/total-evaluation/components/sidebar/feedback-page-navigator/control-buttons.tsx
  src/features/total-evaluation/hooks/use-get-portfolio-feedback-data.ts
Labels: 🔨 Fix

#241 [#236] - 피드백 loading 페이지 QA 작업
  src/common/components/feedback-state-observer/feedback-state-observer.tsx
  src/common/components/toast/toast-config.tsx
  src/common/components/toast/toast.styles.ts
  src/common/hooks/use-toast.ts
  src/common/stories/toast.stories.tsx
  src/features/upload/components/feedback-loading/loading-project-evaluation.tsx
  src/features/upload/constants/loading-constant.ts
  src/features/upload/upload-page.tsx
Labels: 🔨 Fix

#243 [#242] - font 범위 설정
  src/assets/styles/global-styles.ts
Labels: 🔨 Fix

#245 [#242] - font synthesis 제거
  src/assets/styles/global-styles.ts
Labels: 🔨 Fix

#248 [#247] - toast 너비 지정
  src/common/components/toast/toast.styles.ts
Labels: 🧤 Refactor

#250 [#244] - QA: 모바일 로그인 뷰, 랜딩 이미지 , 계정 제한, 헤더 메뉴 중앙 정렬
  src/common/components/layout/header-buttons/header-logo.styles.ts
  src/common/components/layout/header-buttons/total-evaluation/total-evaluation-sidebar-buttons.tsx
  src/common/components/layout/header-navigation/header-navigation-layout.styles.ts
  src/common/components/layout/header-navigation/header-navigation-layout.tsx
  src/common/hooks/use-header-contents.tsx
  src/features/landing/components/helpers-section/detail-improvement.tsx
  src/features/landing/components/helpers-section/projects.tsx
  src/features/landing/components/helpers-section/step-card.tsx
  src/features/landing/components/helpers-section/total-evaluation-grid.tsx
  src/features/landing/landing-page.tsx
  src/features/landing/utils/extract-image-file-name.ts
  src/features/login/components/desktop-view.styles.ts
  src/features/login/components/desktop-view.tsx
  src/features/login/components/mobile-view.styles.ts
  src/features/login/components/mobile-view.tsx
  src/features/login/login-page.tsx
  src/features/upload/components/portfolio-upload/portfolio-upload.tsx
  src/features/upload/services/mutations.ts
  src/route.tsx
Labels: ✨ Feature, 🔨 Fix

#252 [#251] - 포트폴리오 피드백 조회 스타일 수정 (한 줄 요약 Spacing 제거)
  src/features/total-evaluation/components/project-evaluation/project-evaluation.tsx
  src/features/total-evaluation/total-evaluation-page.styles.ts
Labels: 🎨 Style

#260 [#258] - 로그인 페이지 모바일 뷰
  src/features/login/components/custom-buttons/google-auth-button.styles.ts
  src/features/login/components/custom-buttons/google-auth-button.tsx
  src/features/login/components/mobile-view.styles.ts
  src/features/login/components/mobile-view.tsx
Labels: 🎨 Style

#264 [#263] - 허용 계정 추가
  src/features/upload/services/mutations.ts
Labels: ✨ Feature

#268 [#267] - 로그인 페이지 모바일/데스크탑 뷰 통합
  src/features/login/components/desktop-view.tsx
  src/features/login/components/mobile-view.styles.ts
  src/features/login/components/mobile-view.tsx
  src/features/login/login-page.styles.ts
  src/features/login/login-page.tsx
Labels: 🧤 Refactor

#271 [#270] - 정적 계정 허용 리스트 제거
  src/features/upload/components/portfolio-upload/portfolio-upload.tsx
  src/features/upload/services/mutations.ts
Labels: 🧤 Refactor

#273 [#269] - 비로그인 상태일때 toast 제거
  src/common/components/layout/header-buttons/profile-dropdown.tsx
Labels: 🔨 Fix

#286 [#283] - 디자이너 포트폴리오만 업로드 가능하다고 알려주는 토스트 추가
  src/common/components/toast/toast-config.tsx
  src/common/components/toast/toast.styles.ts
  src/common/hooks/use-toast.ts
  src/features/upload/components/feedback-loading/loading-page-evaluation.tsx
  src/features/upload/components/portfolio-upload/portfolio-upload.tsx
  src/features/upload/constants/loading-constant.ts
  src/store/feedback.ts
Labels: ✨ Feature, 🔨 Fix

#288 [#287] - 모달 z-index 관리
  src/common/components/mobile-guard-modal/mobile-guard-modal.tsx
  src/common/components/modal/alert-modal.tsx
  src/common/components/modal/base-modal.styles.ts
  src/common/components/modal/base-modal.tsx
  src/common/components/modal/index.styles.ts
  src/common/components/modal/modal-types.ts
  src/common/hooks/use-get-modal-z-index.ts
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal.tsx
Labels: 🧤 Refactor

#294 [#293] - Behance 링크 추가
  src/common/components/icon/icon.tsx
  src/common/components/layout/footer/footer.tsx
Labels: ✨ Feature

#296 [#295] - z-index 상수로 분리
  src/common/components/layout/common-layout.styles.ts
  src/common/components/layout/header-buttons/profile-dropdown.styles.ts
  src/common/components/layout/header-navigation/header-navigation-layout.styles.ts
  src/common/components/toast/toast.styles.ts
  src/common/constants/z-index.ts
  src/common/hooks/use-get-modal-z-index.ts
  src/features/landing/components/helpers-section/detail-improvement.styles.ts
  src/features/profile/components/recent-feedback-modal/recent-feedback-modal-content.styles.ts
  src/features/total-evaluation/components/custom-buttons/page-location-button.styles.ts
  src/features/total-evaluation/components/project-evaluation/project-evaluation.styles.ts
  src/features/total-evaluation/components/sidebar/base-sidebar-left/base-sidebar-left.styles.ts
  src/features/upload/components/feedback-loading/loading-page-evaluation.styles.ts
Labels: 🧤 Refactor
